lot1: lot1.o HextoTwo.o StringtoHex.o
	gcc lot1.o HextoTwo.o StringtoHex.o -o lot1

lot1.o: lot1.h lot1.c
	gcc -c lot1.c

HextoTwo.o: HextoTwo.c HextoTwo.h
	gcc -c HextoTwo.c

StringtoHex.o: StringtoHex.c StringtoHex.h
	gcc -c StringtoHex.c
